name: Build and Publish Docker

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Lowercase the repo owner
        run: |
                  echo ::set-env name=OWNER::${GITHUB_REPOSITORY_OWNER,,}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          docker build . --file aarch64.Dockerfile --platform linux/arm64 --tag ${{ env.OWNER }}/arm64-code-server:latest --push
          docker build . --file x86_64.Dockerfile --platform linux/amd64 --tag ${{ env.OWNER }}/amd64-code-server:latest --push
          docker manifest create ${{ env.OWNER }}/code-server:latest ${{ env.OWNER }}/arm64-code-server:latest ${{ env.OWNER }}/amd64-code-server:latest
          docker manifest push ${{ env.OWNER }}/code-server:latest